#集群配置
flink.dir: /home/experiment/wj2/env/flink-1.11.0
#配置yarn的主节点：端口
yarn.ip.port: http://localhost:8088

ip: 0.0.0.0
query.distance: 10s
job.listen.distance: 10s
#配置本地promethus的ip：端口
prometheus.ip.port: http://localhost:9090
#判断流任务还是批任务
flink.job.type: stream
stream.stable.times: 2
stream.stable.time: 1min
stream.listen.distance: 1min

#user和keytab的配置在.bashrc|| .profile || .bash_profile 文件中
#krb5Location是跟keytab同一个目录的krb5.conf文件
kerberos:
  user: #FL_user
  keytab: # 路径
  krb5Location: # 路径

#性能指标：权重
metrics:
  flink_taskmanager_Status_JVM_Memory_Heap_Used/(flink_taskmanager_Status_JVM_Memory_Heap_Committed-134217728): 0.1
  flink_taskmanager_Status_JVM_Memory_NonHeap_Used/flink_taskmanager_Status_JVM_Memory_NonHeap_Committed : 0.2
  flink_taskmanager_Status_JVM_CPU_Load: 0.1
  flink_taskmanager_Status_Network_AvailableMemorySegments/flink_taskmanager_Status_Network_TotalMemorySegments : 0.2
 # time: 0.2
  latency: 0.2
  consumption.ratio: 0.2

#flink参数：取值
parameters:
  taskmanager.memory.process.size: [4g,8g,10g,16g,20g]
  taskmanager.numberOfTaskSlots: [4,6,8,10,12]
  taskmanager.memory.network.fraction: [0.05,0.1,0.15,0.2]
  taskmanager.memory.managed.fraction: [0.3,0.4,0.5,0.6]

#性能目标
target: 0.9
job.submit.cmd: ./bin/flink  run -m yarn-cluster  -c  org.apache.flink.benchmark.Benchmark  /home/experiment/wj2/project/flinl-benchmark-master/flink-tpcds_2020_12_09/target/flink-tpcds-0.1-SNAPSHOT-jar-with-depecies.jar --database tpcds_bin_orc_100 --hive_conf   /home/experiment/wj2/env/apache-hiv3.4-bin/conf  --queries q99.sql
memory.slot.min: 0.5g
memory.slot.max: 2g
taskmanager.memory.network.min: 512m
taskmanager.memory.network.max: 4096m
time.reduce.ratio: 0.2
max.latency: 1s
consumption.target: 50000
genetic.iteration.max: 5
bayes.init.points: 3
bayes.iteration.max: 7
python.cmd: python3

rule1: parallelism.default/taskmanager.numberOfTaskSlots <= 6
rule2: 0.5g<=taskmanager.memory.process.size/taskmanager.numberOfTaskSlots<=3g
rule3: 256m<=taskmanager.memory.process.size*taskmanager.memory.network.fraction <=4G









